# Generated by Django 3.2.5 on 2021-07-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_order_items_orderitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
